apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  storageClassName: ""  # Leave empty if you don't want to associate it with a storage class
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  awsElasticBlockStore:
    volumeID: vol-0369ba539fbf8d73d
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-html #same name should be given what provided in vloumes 
      volumes:
      - name: nginx-html #same name should be given
        persistentVolumeClaim: # this is the PVC
          claimName: ebs-static-pvc
